name: IRpractical
channels:
  - conda-forge
  - defaults
  - gurobi
dependencies:
  - python==3.11.4
  - cvxpy==1.3.2
  - cvxopt==1.3.0
  - matplotlib==3.8.0
  - pyyaml==6.0.1
  - numpy>=1.25.1,<2
  - pip
  - networkx==3.3
  - pip:
    - numpy>=1.25.1,<2
    - gurobipy==12.0.1
    - gurobi-logtools==3.2.0